[package]
name = "remslice"
version = "0.3.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
cli-clipboard = "0.4.0"
home = "0.5.9"
